
language: android
addons:
    sonarcloud:
        token:
            secure: "QqwWbcPHPj6oxmW+m6dKUHGr2EMeiKSb9ZZWp8saFRol5k031juForE6kD2u6DmcUSbOIk4ZZvT7vnWgh5y1DxEUtpP9FB90enykKOmEU3zJI9CrAZoKOuqwiFTdjv2rujqskGPnQBhzwAS0JiyVCHAGQJUV94aSaVeiGHVUHCaPDZWqVdzsfNvEMgZpY+Z7eoeCIghZkO8gOgshO7g23PJgkxMPa8WaIhVqK3CE8uh28OH0Blil64GyeV9LpiRN9L60StGW7QE/3/x5GiUhSohGddPGVmHeWiB6PmR5L/WU3iokJ9ybLXlrZLMyFNtAxYMIwhQNrmbH3G8wHJJVBlzLBhFM2oQEtJzSkN/HqjgQ1GzWoog/aHwPfKH8tTFQXanOrMgtdMTTWYR0jVtoCCiqV16E3pEtfhndu4oYwMkg0VxQegwTuGZpXjwej+y4noFPbul95c6OLtz0msc2ilzZeK0VHXCUws/zjer4QGxNmpUqm9zhYJrRQbWA2MpRpZd6SI/6yppbse+Aqhs9b0lBmza6nItzE3DoajLZZk8UeKnrhQSC0gm4sEco3iBF/xBkM94I8nWBKwXmlDGkEkQoSISnvP3C9JnZUAYp5XVpDo5jRy+QijF9KKt6yXw9BlR+8D4FAfQrdsoxLEI4q04GV4DE6mq4qCwODvN50Jw="
jdk: oraclejdk8
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
  - secure: NDfLURDgVvJqcsHeIWPrcONfhDHeIa52KfyK+vEGrESf+MhxtzXs/e6SsXF8ZGY2WpmiMGDIBA/ZPW+/bXn5C9DtZvkXOUXG+pfEzp5Gp7XwEPgZF7o/KbkvX+7K2mSLNRKZMIIfI2Ct3zeFX5rKnfbo726Hh02RnTEWjo3ghtXbdNHp4x4fCk6AC8OHc90gmRUtHKUF89+eegr5E36Vu0LIK7/jwemG+yXe/CkDX7/8QjOQipObdk+M0nGJXvwfxM6B+K2NXzjx1/KQ1zmaQTNzKTWHPW35nfJ/lQH+XsFj0KjrVbKg6n7P8mVZYFw7TmKWT3piWFXejWMdqLwxaza0Q+bTNDAn3O931VN+9EuZROoUR3tlHEMMv2CFr4TVs6kF0pyVJYL2gzAsM1s0F6kxqGvXLGBj68jXesnQkKQntjZ60crCu2xwICaJ9XTN/bKLk8JLH2kELq5bCv8R+BbBx+1TZcjcrnX3BxzMZBAMjOPbGKnHDhdVxrtQstLawxgI0hIeEcQNWM3xXByOfx+rOXDtMsVMM76AqR9FICmkelKJmklFdP4b0qHxxEK8YAtYOlRoKLy2Ywa7Cn3rG3bAr78k59TWAAbyfLIrkd0nMqTVUSg24wF35abCIH5UDcQI+U35Yamzi21/R/zRszjBCw1+IEJ4pcb0u1+B4JU=
  - secure: myLa+mYy0XrC/vjwRfpCOcdCiBWXj9bCwK7ub+FG5pdrquiHw6gxCD0wBABEmPyNYIRj2iqe0fhtwlGCNBVWeltxpXu1KhTMZ0mMsg+RiHdKEMrrcEX64Am66XOHQQ7tY2OHLJQgUmVuhRSx8t5SFcaNM0Rnc4jBfOJPM23d2f4egM3fMJTIQkqqPB76ntacY/tFSxAsFgUyT4tINiNhL8FGrY9PkOrvreWaIdwa181999SaRbsTxKEhIHiN1/nkxtiuNox3nfpUULuP3YNBeifIL1U/hVwzboxUlTXy6qRTa2OuUNIGZQu9XRpxWMG/kfpsfkM1K5kPEJEuy3NA19p+5EcizBq+3XzJBoPN4RGdJTEAmTYxdU3q1y8Dni+wPem/klspIJV4EHes55WEjlAm96dnSPP0KihjUsUooU+d9O7YJCRJFCLrtir9s2Hsx+8DHjta8AjMdf2LClWvY0mE7iexQSG3phoha9mmcCQWXJNStY3+hxWUwTFCqpXeCLk3O3ExxEFVTqOEG/hufhSCgnIOgNe742oTBSAFxKG4wJXp7erb0IlP8Ne/3OOM7TOVYSOPcJgYzXxBRqCV0reSyPm9fgsGzuf0jUTZLMkhOsfqADrg9/JwcYW3J17h60tY6eyZiwWsHmhxkDGI+LnFUCiLGQP5Ecf3s0qwOGA=
  - secure: Lyy3LVldYFeK65Oz/hWxQ48OE0z/id/1lC/uIMZwaFyaNrSMuyhV14X4ZBuQquXD7XzswAkOi+5nsVcXGZ1AcI+DWJv2dy2U/yaLcn/uaSDty5xXEhmO3E+Mgmsul93TcdYYTPfvvC+P1JC17yOeff7U52EQCZsusXo7PBPxs7NWG0UwYE/WKaQ1zaB9bRxr1+JwvfIr9zxIlZodzA7Pctup+3kjKw5s0c/YC9gIr1ahL2Ux/X9LwQRCZE8eTwd/UCIyFZvDoQJ1v86eVC1sg5H55IYpcEJt33ld0s4Hdg4tOnL59GgJcR1+ElqTnVCv620VHwYtZZEUz+EVAsGfoo3atIO0u9cZH28Obk5pk47nodQLrFSIV+kfQnKbeJ+omiRMSJx3er0JBdiyFELVmfxa09bzqKoARR8HLjCFQlmS855JE+kgqiPFwmK11S+T1wd5rTHRvX7RAjK0jdgn00N1uT0tEgJUm4d2A50EokdT2zWXaFvhzvAgjGh/AwRtReWM4vo6VOjKA5+mGE+pvlAwc2xVL1cjnS+DE/02Lc0DRgYaJga61XbApMwsJ6ZUQbY3M8kBIxTBWIj6CUyBY0dUuyvDMV97+YYz7sjSQ+ZIcFxJ7zyhAN7TxiUYbgvVgIKbgaG5MPB7/HFM+C7vg81xgEP2GL4d5/UOXE52/qU=
  - secure: XggRNV3zj5Llstv6UR0gmxy1eKHjubwTq9yVhtYDqr+xDSaqB8JGmQbDwHWQWCOGotEW3pTXiaOfk+xZDT+p5uXmncAaVfZDMWji2v8kOqyunovi5BOw4dKzNR9C4zM9aJ5EWaE8X5i55KpVTMRJh3KmfH+5jwOWWslWDr2hoNjQqaTrZ66CSaEK2EH6QDuhYTUFK37DjRekVN90eLt1tkz4os1Z/Vhx9xWQnxncxNEkhFFFIRF7pyiqyyTDn89rtNdZSHIGQ6uPmzJuyc4Ng3BgWBK8ieC6aDCR44zP5KwayQI7qxrrCS9g4Am8snmE8pZS5Px4NTW7/dcT8vjVmpsAPQ6dmHtCMnJ6XDUpjhkvIOSFcuuJxK2Y2lTH+I1ItTpyN40UlvcbfiAwMOizT/IlqCdrNg+OtIsLFOO1t3EMij2PqEiB0jhp2Fy0Oi9LUJ6pLLUbgJpSPqnzXCo4zZ9Yx4Zgh4R14Zi0uFfQDiVSffVbktTkdZ2o1FBBVUcMFwrMXYR+jfsI+FNxiHJs8u6HnJjQjUT2pnv+LkcInZUqxVL1VpOJF9zEKlL4+p9zUvkXF29ljFrnkPeQf527VxYn9qvKwz0vGK1kfyBJIWonfSJ9jEyulQVJ8mrsCb+lXGk75MPucnMEqDrBEOtmAj7zgtDsbXgx/yQEojJdCIA=
android:
  components:
  - platform-tools
  - tools
  - android-28
  - build-tools-28.0.3
  - extra
before_deploy:
- cd -
- sh set_tags.sh
script:
- cd final
- chmod +x gradlew
- "./gradlew clean build"
- cd ..
- sonar-scanner
deploy:
  provider: releases
  api_key:
    secure: W39sPYLSR/+XWmKJxGpS6DVgIPxKPC9V/w+3/GJMzNFTaPWDnHM+5JJjMsT/JHAbq9QJ3n1nwZ+WYxH0u2fmNAvjdN1vnkHQ7y6WmdPYXeNsQDBBwGMx6kq7OfXjbJKUXj+aXDwF4cuAcjcL4MHsZliug1Tx5jQmNFRtFCdfDrxAvimHKAMM0nN7BbLFOzsHSwIzG1kxh5PrRVSFFigJHUzMSgY85SFYcSnaM2MosQixnWyjeIq8+fm72pr93yVQJz+MJ9WJZZFR2uh1NXs1X4pIRPC4aFxkCqZVa1+RzbhWQGsyeHRrXs4oafhxfqh3k8e00LbWawAuO9QxFraWY+UuEDNHWl4771nn6oQak1DlnCihLLnHU9MIpZryXlCHdPqCKGhqQWOYpg2q+DrXGuXleuuMa9y5IS/yYF57bLfeYePaJGscxvbSILaaRWXRdHDqDxSPbU2ILnxNLdLhkpskCC1KFKOy1l4DN3htayUzo+iP9c7sukifHGrtCDocy8uwGj9bcWHJml/Bj5fuv2P7qUQGCFsklx7GXLfXrZGT5SW4n5ezZrBVmZAEP56SlhOuHjNxZlHzyf+SgYuNBpYDrwCi99HMOimCwvzynTniZpEcfEo3bfEzJGn0DBWO0BeASDY4+OCKCo50oyfUI2tmhYXAsBLnfJwzpg3Hn7A=
  file: final/app/release/CalidadSpaceG4.apk
  skip_cleanup: true
  overwite: true
  on:
    branch: master
    repo: RubenBernabe/CalidadSpace
