sudo: required
language: android
jdk: oraclejdk8
env:
  global:
  - secure: NDfLURDgVvJqcsHeIWPrcONfhDHeIa52KfyK+vEGrESf+MhxtzXs/e6SsXF8ZGY2WpmiMGDIBA/ZPW+/bXn5C9DtZvkXOUXG+pfEzp5Gp7XwEPgZF7o/KbkvX+7K2mSLNRKZMIIfI2Ct3zeFX5rKnfbo726Hh02RnTEWjo3ghtXbdNHp4x4fCk6AC8OHc90gmRUtHKUF89+eegr5E36Vu0LIK7/jwemG+yXe/CkDX7/8QjOQipObdk+M0nGJXvwfxM6B+K2NXzjx1/KQ1zmaQTNzKTWHPW35nfJ/lQH+XsFj0KjrVbKg6n7P8mVZYFw7TmKWT3piWFXejWMdqLwxaza0Q+bTNDAn3O931VN+9EuZROoUR3tlHEMMv2CFr4TVs6kF0pyVJYL2gzAsM1s0F6kxqGvXLGBj68jXesnQkKQntjZ60crCu2xwICaJ9XTN/bKLk8JLH2kELq5bCv8R+BbBx+1TZcjcrnX3BxzMZBAMjOPbGKnHDhdVxrtQstLawxgI0hIeEcQNWM3xXByOfx+rOXDtMsVMM76AqR9FICmkelKJmklFdP4b0qHxxEK8YAtYOlRoKLy2Ywa7Cn3rG3bAr78k59TWAAbyfLIrkd0nMqTVUSg24wF35abCIH5UDcQI+U35Yamzi21/R/zRszjBCw1+IEJ4pcb0u1+B4JU=
  - secure: myLa+mYy0XrC/vjwRfpCOcdCiBWXj9bCwK7ub+FG5pdrquiHw6gxCD0wBABEmPyNYIRj2iqe0fhtwlGCNBVWeltxpXu1KhTMZ0mMsg+RiHdKEMrrcEX64Am66XOHQQ7tY2OHLJQgUmVuhRSx8t5SFcaNM0Rnc4jBfOJPM23d2f4egM3fMJTIQkqqPB76ntacY/tFSxAsFgUyT4tINiNhL8FGrY9PkOrvreWaIdwa181999SaRbsTxKEhIHiN1/nkxtiuNox3nfpUULuP3YNBeifIL1U/hVwzboxUlTXy6qRTa2OuUNIGZQu9XRpxWMG/kfpsfkM1K5kPEJEuy3NA19p+5EcizBq+3XzJBoPN4RGdJTEAmTYxdU3q1y8Dni+wPem/klspIJV4EHes55WEjlAm96dnSPP0KihjUsUooU+d9O7YJCRJFCLrtir9s2Hsx+8DHjta8AjMdf2LClWvY0mE7iexQSG3phoha9mmcCQWXJNStY3+hxWUwTFCqpXeCLk3O3ExxEFVTqOEG/hufhSCgnIOgNe742oTBSAFxKG4wJXp7erb0IlP8Ne/3OOM7TOVYSOPcJgYzXxBRqCV0reSyPm9fgsGzuf0jUTZLMkhOsfqADrg9/JwcYW3J17h60tY6eyZiwWsHmhxkDGI+LnFUCiLGQP5Ecf3s0qwOGA=

android:
  components:
  - platform-tools
  - tools
  - android-28
  - build-tools-28.0.3
  - extra

before_deploy:
- cd -
- sh set_tags.sh
script:
- cd final
- chmod +x gradlew
- "./gradlew clean build"
deploy:
  provider: releases
  api_key:
    secure: W39sPYLSR/+XWmKJxGpS6DVgIPxKPC9V/w+3/GJMzNFTaPWDnHM+5JJjMsT/JHAbq9QJ3n1nwZ+WYxH0u2fmNAvjdN1vnkHQ7y6WmdPYXeNsQDBBwGMx6kq7OfXjbJKUXj+aXDwF4cuAcjcL4MHsZliug1Tx5jQmNFRtFCdfDrxAvimHKAMM0nN7BbLFOzsHSwIzG1kxh5PrRVSFFigJHUzMSgY85SFYcSnaM2MosQixnWyjeIq8+fm72pr93yVQJz+MJ9WJZZFR2uh1NXs1X4pIRPC4aFxkCqZVa1+RzbhWQGsyeHRrXs4oafhxfqh3k8e00LbWawAuO9QxFraWY+UuEDNHWl4771nn6oQak1DlnCihLLnHU9MIpZryXlCHdPqCKGhqQWOYpg2q+DrXGuXleuuMa9y5IS/yYF57bLfeYePaJGscxvbSILaaRWXRdHDqDxSPbU2ILnxNLdLhkpskCC1KFKOy1l4DN3htayUzo+iP9c7sukifHGrtCDocy8uwGj9bcWHJml/Bj5fuv2P7qUQGCFsklx7GXLfXrZGT5SW4n5ezZrBVmZAEP56SlhOuHjNxZlHzyf+SgYuNBpYDrwCi99HMOimCwvzynTniZpEcfEo3bfEzJGn0DBWO0BeASDY4+OCKCo50oyfUI2tmhYXAsBLnfJwzpg3Hn7A=
  file: "app/build/outputs/apk/release/CalidadSpaceG4.apk"
  skip_cleanup: true
  overwite: true
  on:
    branch: master
    repo: RubenBernabe/CalidadSpace
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
