language: android
android:
  components:
    - android-28
    - build-tools-28.0.3
    - sys-img-armeabi-v7a-google_apis-28
    - android-24
    - build-tools-24.0.1
before_script:
  - echo no | android create avd --force -n test -t android-28 --abi google_apis/armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
script:
  - cd final
  - chmod +x gradlew
  - ./gradlew build